// Generated by rstantools.  Do not edit by hand.

#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_varlasso_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_varlasso");
    reader.add_event(197, 195, "end", "model_varlasso");
    return reader;
}
#include <stan_meta_header.hpp>
class model_varlasso
  : public stan::model::model_base_crtp<model_varlasso> {
private:
        int n_time;
        int n_spp;
        int n_off;
        int n_q;
        int n_r;
        std::vector<int> id_q;
        std::vector<int> id_r;
        std::vector<std::vector<int> > rc_off;
        int n_pos;
        std::vector<int> time_index;
        std::vector<int> species_index;
        std::vector<double> yy;
        std::vector<double> b_mu;
        std::vector<double> b_sd;
        std::vector<double> b_mu_diag;
        std::vector<double> b_sd_diag;
        int off_diag_priors;
        double sigma_proc_mu;
        double sigma_obs_mu;
        double sigma_proc_sd;
        double sigma_obs_sd;
        double nu_known;
        double global_scale;
        double slab_scale;
        double slab_df;
        double sigma_scale_df;
        double sigma_scale_sd;
        int priors_only;
        int est_trend;
        int est_nu;
        int est_hs;
        int est_lambda;
        double dummy;
public:
    model_varlasso(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_varlasso(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_varlasso_namespace::model_varlasso";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 2;
            context__.validate_dims("data initialization", "n_time", "int", context__.to_vec());
            n_time = int(0);
            vals_i__ = context__.vals_i("n_time");
            pos__ = 0;
            n_time = vals_i__[pos__++];
            check_greater_or_equal(function__, "n_time", n_time, 0);
            current_statement_begin__ = 3;
            context__.validate_dims("data initialization", "n_spp", "int", context__.to_vec());
            n_spp = int(0);
            vals_i__ = context__.vals_i("n_spp");
            pos__ = 0;
            n_spp = vals_i__[pos__++];
            check_greater_or_equal(function__, "n_spp", n_spp, 0);
            current_statement_begin__ = 4;
            context__.validate_dims("data initialization", "n_off", "int", context__.to_vec());
            n_off = int(0);
            vals_i__ = context__.vals_i("n_off");
            pos__ = 0;
            n_off = vals_i__[pos__++];
            check_greater_or_equal(function__, "n_off", n_off, 0);
            current_statement_begin__ = 5;
            context__.validate_dims("data initialization", "n_q", "int", context__.to_vec());
            n_q = int(0);
            vals_i__ = context__.vals_i("n_q");
            pos__ = 0;
            n_q = vals_i__[pos__++];
            check_greater_or_equal(function__, "n_q", n_q, 1);
            current_statement_begin__ = 6;
            context__.validate_dims("data initialization", "n_r", "int", context__.to_vec());
            n_r = int(0);
            vals_i__ = context__.vals_i("n_r");
            pos__ = 0;
            n_r = vals_i__[pos__++];
            check_greater_or_equal(function__, "n_r", n_r, 1);
            current_statement_begin__ = 7;
            validate_non_negative_index("id_q", "n_spp", n_spp);
            context__.validate_dims("data initialization", "id_q", "int", context__.to_vec(n_spp));
            id_q = std::vector<int>(n_spp, int(0));
            vals_i__ = context__.vals_i("id_q");
            pos__ = 0;
            size_t id_q_k_0_max__ = n_spp;
            for (size_t k_0__ = 0; k_0__ < id_q_k_0_max__; ++k_0__) {
                id_q[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 8;
            validate_non_negative_index("id_r", "n_spp", n_spp);
            context__.validate_dims("data initialization", "id_r", "int", context__.to_vec(n_spp));
            id_r = std::vector<int>(n_spp, int(0));
            vals_i__ = context__.vals_i("id_r");
            pos__ = 0;
            size_t id_r_k_0_max__ = n_spp;
            for (size_t k_0__ = 0; k_0__ < id_r_k_0_max__; ++k_0__) {
                id_r[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 9;
            validate_non_negative_index("rc_off", "n_off", n_off);
            validate_non_negative_index("rc_off", "2", 2);
            context__.validate_dims("data initialization", "rc_off", "int", context__.to_vec(n_off,2));
            rc_off = std::vector<std::vector<int> >(n_off, std::vector<int>(2, int(0)));
            vals_i__ = context__.vals_i("rc_off");
            pos__ = 0;
            size_t rc_off_k_0_max__ = n_off;
            size_t rc_off_k_1_max__ = 2;
            for (size_t k_1__ = 0; k_1__ < rc_off_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < rc_off_k_0_max__; ++k_0__) {
                    rc_off[k_0__][k_1__] = vals_i__[pos__++];
                }
            }
            size_t rc_off_i_0_max__ = n_off;
            size_t rc_off_i_1_max__ = 2;
            for (size_t i_0__ = 0; i_0__ < rc_off_i_0_max__; ++i_0__) {
                for (size_t i_1__ = 0; i_1__ < rc_off_i_1_max__; ++i_1__) {
                    check_greater_or_equal(function__, "rc_off[i_0__][i_1__]", rc_off[i_0__][i_1__], 0);
                }
            }
            current_statement_begin__ = 10;
            context__.validate_dims("data initialization", "n_pos", "int", context__.to_vec());
            n_pos = int(0);
            vals_i__ = context__.vals_i("n_pos");
            pos__ = 0;
            n_pos = vals_i__[pos__++];
            check_greater_or_equal(function__, "n_pos", n_pos, 0);
            current_statement_begin__ = 11;
            validate_non_negative_index("time_index", "n_pos", n_pos);
            context__.validate_dims("data initialization", "time_index", "int", context__.to_vec(n_pos));
            time_index = std::vector<int>(n_pos, int(0));
            vals_i__ = context__.vals_i("time_index");
            pos__ = 0;
            size_t time_index_k_0_max__ = n_pos;
            for (size_t k_0__ = 0; k_0__ < time_index_k_0_max__; ++k_0__) {
                time_index[k_0__] = vals_i__[pos__++];
            }
            size_t time_index_i_0_max__ = n_pos;
            for (size_t i_0__ = 0; i_0__ < time_index_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "time_index[i_0__]", time_index[i_0__], 0);
            }
            current_statement_begin__ = 12;
            validate_non_negative_index("species_index", "n_pos", n_pos);
            context__.validate_dims("data initialization", "species_index", "int", context__.to_vec(n_pos));
            species_index = std::vector<int>(n_pos, int(0));
            vals_i__ = context__.vals_i("species_index");
            pos__ = 0;
            size_t species_index_k_0_max__ = n_pos;
            for (size_t k_0__ = 0; k_0__ < species_index_k_0_max__; ++k_0__) {
                species_index[k_0__] = vals_i__[pos__++];
            }
            size_t species_index_i_0_max__ = n_pos;
            for (size_t i_0__ = 0; i_0__ < species_index_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "species_index[i_0__]", species_index[i_0__], 0);
            }
            current_statement_begin__ = 13;
            validate_non_negative_index("yy", "n_pos", n_pos);
            context__.validate_dims("data initialization", "yy", "double", context__.to_vec(n_pos));
            yy = std::vector<double>(n_pos, double(0));
            vals_r__ = context__.vals_r("yy");
            pos__ = 0;
            size_t yy_k_0_max__ = n_pos;
            for (size_t k_0__ = 0; k_0__ < yy_k_0_max__; ++k_0__) {
                yy[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 14;
            validate_non_negative_index("b_mu", "n_off", n_off);
            context__.validate_dims("data initialization", "b_mu", "double", context__.to_vec(n_off));
            b_mu = std::vector<double>(n_off, double(0));
            vals_r__ = context__.vals_r("b_mu");
            pos__ = 0;
            size_t b_mu_k_0_max__ = n_off;
            for (size_t k_0__ = 0; k_0__ < b_mu_k_0_max__; ++k_0__) {
                b_mu[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 15;
            validate_non_negative_index("b_sd", "n_off", n_off);
            context__.validate_dims("data initialization", "b_sd", "double", context__.to_vec(n_off));
            b_sd = std::vector<double>(n_off, double(0));
            vals_r__ = context__.vals_r("b_sd");
            pos__ = 0;
            size_t b_sd_k_0_max__ = n_off;
            for (size_t k_0__ = 0; k_0__ < b_sd_k_0_max__; ++k_0__) {
                b_sd[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 16;
            validate_non_negative_index("b_mu_diag", "n_spp", n_spp);
            context__.validate_dims("data initialization", "b_mu_diag", "double", context__.to_vec(n_spp));
            b_mu_diag = std::vector<double>(n_spp, double(0));
            vals_r__ = context__.vals_r("b_mu_diag");
            pos__ = 0;
            size_t b_mu_diag_k_0_max__ = n_spp;
            for (size_t k_0__ = 0; k_0__ < b_mu_diag_k_0_max__; ++k_0__) {
                b_mu_diag[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 17;
            validate_non_negative_index("b_sd_diag", "n_spp", n_spp);
            context__.validate_dims("data initialization", "b_sd_diag", "double", context__.to_vec(n_spp));
            b_sd_diag = std::vector<double>(n_spp, double(0));
            vals_r__ = context__.vals_r("b_sd_diag");
            pos__ = 0;
            size_t b_sd_diag_k_0_max__ = n_spp;
            for (size_t k_0__ = 0; k_0__ < b_sd_diag_k_0_max__; ++k_0__) {
                b_sd_diag[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 18;
            context__.validate_dims("data initialization", "off_diag_priors", "int", context__.to_vec());
            off_diag_priors = int(0);
            vals_i__ = context__.vals_i("off_diag_priors");
            pos__ = 0;
            off_diag_priors = vals_i__[pos__++];
            current_statement_begin__ = 19;
            context__.validate_dims("data initialization", "sigma_proc_mu", "double", context__.to_vec());
            sigma_proc_mu = double(0);
            vals_r__ = context__.vals_r("sigma_proc_mu");
            pos__ = 0;
            sigma_proc_mu = vals_r__[pos__++];
            check_greater_or_equal(function__, "sigma_proc_mu", sigma_proc_mu, 0);
            current_statement_begin__ = 20;
            context__.validate_dims("data initialization", "sigma_obs_mu", "double", context__.to_vec());
            sigma_obs_mu = double(0);
            vals_r__ = context__.vals_r("sigma_obs_mu");
            pos__ = 0;
            sigma_obs_mu = vals_r__[pos__++];
            check_greater_or_equal(function__, "sigma_obs_mu", sigma_obs_mu, 0);
            current_statement_begin__ = 21;
            context__.validate_dims("data initialization", "sigma_proc_sd", "double", context__.to_vec());
            sigma_proc_sd = double(0);
            vals_r__ = context__.vals_r("sigma_proc_sd");
            pos__ = 0;
            sigma_proc_sd = vals_r__[pos__++];
            check_greater_or_equal(function__, "sigma_proc_sd", sigma_proc_sd, 0);
            current_statement_begin__ = 22;
            context__.validate_dims("data initialization", "sigma_obs_sd", "double", context__.to_vec());
            sigma_obs_sd = double(0);
            vals_r__ = context__.vals_r("sigma_obs_sd");
            pos__ = 0;
            sigma_obs_sd = vals_r__[pos__++];
            check_greater_or_equal(function__, "sigma_obs_sd", sigma_obs_sd, 0);
            current_statement_begin__ = 23;
            context__.validate_dims("data initialization", "nu_known", "double", context__.to_vec());
            nu_known = double(0);
            vals_r__ = context__.vals_r("nu_known");
            pos__ = 0;
            nu_known = vals_r__[pos__++];
            check_greater_or_equal(function__, "nu_known", nu_known, 0);
            current_statement_begin__ = 24;
            context__.validate_dims("data initialization", "global_scale", "double", context__.to_vec());
            global_scale = double(0);
            vals_r__ = context__.vals_r("global_scale");
            pos__ = 0;
            global_scale = vals_r__[pos__++];
            check_greater_or_equal(function__, "global_scale", global_scale, 0);
            current_statement_begin__ = 25;
            context__.validate_dims("data initialization", "slab_scale", "double", context__.to_vec());
            slab_scale = double(0);
            vals_r__ = context__.vals_r("slab_scale");
            pos__ = 0;
            slab_scale = vals_r__[pos__++];
            check_greater_or_equal(function__, "slab_scale", slab_scale, 0);
            current_statement_begin__ = 26;
            context__.validate_dims("data initialization", "slab_df", "double", context__.to_vec());
            slab_df = double(0);
            vals_r__ = context__.vals_r("slab_df");
            pos__ = 0;
            slab_df = vals_r__[pos__++];
            check_greater_or_equal(function__, "slab_df", slab_df, 0);
            current_statement_begin__ = 27;
            context__.validate_dims("data initialization", "sigma_scale_df", "double", context__.to_vec());
            sigma_scale_df = double(0);
            vals_r__ = context__.vals_r("sigma_scale_df");
            pos__ = 0;
            sigma_scale_df = vals_r__[pos__++];
            check_greater_or_equal(function__, "sigma_scale_df", sigma_scale_df, 0);
            current_statement_begin__ = 28;
            context__.validate_dims("data initialization", "sigma_scale_sd", "double", context__.to_vec());
            sigma_scale_sd = double(0);
            vals_r__ = context__.vals_r("sigma_scale_sd");
            pos__ = 0;
            sigma_scale_sd = vals_r__[pos__++];
            check_greater_or_equal(function__, "sigma_scale_sd", sigma_scale_sd, 0);
            current_statement_begin__ = 29;
            context__.validate_dims("data initialization", "priors_only", "int", context__.to_vec());
            priors_only = int(0);
            vals_i__ = context__.vals_i("priors_only");
            pos__ = 0;
            priors_only = vals_i__[pos__++];
            current_statement_begin__ = 30;
            context__.validate_dims("data initialization", "est_trend", "int", context__.to_vec());
            est_trend = int(0);
            vals_i__ = context__.vals_i("est_trend");
            pos__ = 0;
            est_trend = vals_i__[pos__++];
            // initialize transformed data variables
            current_statement_begin__ = 33;
            est_nu = int(0);
            stan::math::fill(est_nu, std::numeric_limits<int>::min());
            current_statement_begin__ = 34;
            est_hs = int(0);
            stan::math::fill(est_hs, std::numeric_limits<int>::min());
            current_statement_begin__ = 35;
            est_lambda = int(0);
            stan::math::fill(est_lambda, std::numeric_limits<int>::min());
            current_statement_begin__ = 36;
            dummy = double(0);
            stan::math::fill(dummy, DUMMY_VAR__);
            // execute transformed data statements
            current_statement_begin__ = 38;
            stan::math::assign(est_nu, 0);
            current_statement_begin__ = 39;
            stan::math::assign(est_hs, 0);
            current_statement_begin__ = 40;
            stan::math::assign(est_lambda, 0);
            current_statement_begin__ = 41;
            stan::math::assign(dummy, 0);
            current_statement_begin__ = 43;
            if (as_bool(logical_eq(off_diag_priors, 1))) {
                current_statement_begin__ = 44;
                stan::math::assign(est_nu, 1);
                current_statement_begin__ = 45;
                if (as_bool(logical_gt(nu_known, 0))) {
                    current_statement_begin__ = 45;
                    stan::math::assign(est_nu, 0);
                }
            }
            current_statement_begin__ = 47;
            if (as_bool(logical_eq(off_diag_priors, 1))) {
                current_statement_begin__ = 47;
                stan::math::assign(est_lambda, 1);
            }
            current_statement_begin__ = 48;
            if (as_bool(logical_eq(off_diag_priors, 2))) {
                current_statement_begin__ = 48;
                stan::math::assign(est_lambda, 1);
            }
            current_statement_begin__ = 49;
            if (as_bool(logical_eq(off_diag_priors, 3))) {
                current_statement_begin__ = 49;
                stan::math::assign(est_hs, 1);
            }
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 52;
            validate_non_negative_index("sigma_obs", "n_r", n_r);
            num_params_r__ += (1 * n_r);
            current_statement_begin__ = 53;
            num_params_r__ += 1;
            current_statement_begin__ = 54;
            validate_non_negative_index("B_z", "n_off", n_off);
            num_params_r__ += n_off;
            current_statement_begin__ = 55;
            validate_non_negative_index("Bdiag", "n_spp", n_spp);
            num_params_r__ += n_spp;
            current_statement_begin__ = 56;
            validate_non_negative_index("x0", "n_spp", n_spp);
            num_params_r__ += n_spp;
            current_statement_begin__ = 57;
            validate_non_negative_index("U", "(est_trend * n_spp)", (est_trend * n_spp));
            num_params_r__ += (est_trend * n_spp);
            current_statement_begin__ = 58;
            validate_non_negative_index("nu", "est_nu", est_nu);
            num_params_r__ += est_nu;
            current_statement_begin__ = 59;
            validate_non_negative_index("lambda2", "(est_lambda * n_off)", (est_lambda * n_off));
            num_params_r__ += (est_lambda * n_off);
            current_statement_begin__ = 60;
            validate_non_negative_index("c2_hs", "est_hs", est_hs);
            num_params_r__ += est_hs;
            current_statement_begin__ = 61;
            validate_non_negative_index("lambda", "(est_hs * n_off)", (est_hs * n_off));
            num_params_r__ += (1 * (est_hs * n_off));
            current_statement_begin__ = 62;
            validate_non_negative_index("sigma_proc", "n_q", n_q);
            num_params_r__ += (1 * n_q);
            current_statement_begin__ = 63;
            validate_non_negative_index("devs", "n_spp", n_spp);
            validate_non_negative_index("devs", "(n_time - 1)", (n_time - 1));
            num_params_r__ += (n_spp * (n_time - 1));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_varlasso() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 52;
        if (!(context__.contains_r("sigma_obs")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma_obs missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma_obs");
        pos__ = 0U;
        validate_non_negative_index("sigma_obs", "n_r", n_r);
        context__.validate_dims("parameter initialization", "sigma_obs", "double", context__.to_vec(n_r));
        std::vector<double> sigma_obs(n_r, double(0));
        size_t sigma_obs_k_0_max__ = n_r;
        for (size_t k_0__ = 0; k_0__ < sigma_obs_k_0_max__; ++k_0__) {
            sigma_obs[k_0__] = vals_r__[pos__++];
        }
        size_t sigma_obs_i_0_max__ = n_r;
        for (size_t i_0__ = 0; i_0__ < sigma_obs_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lb_unconstrain(0, sigma_obs[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma_obs: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 53;
        if (!(context__.contains_r("sigma_scale")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma_scale missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma_scale");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "sigma_scale", "double", context__.to_vec());
        double sigma_scale(0);
        sigma_scale = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, sigma_scale);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma_scale: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 54;
        if (!(context__.contains_r("B_z")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable B_z missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("B_z");
        pos__ = 0U;
        validate_non_negative_index("B_z", "n_off", n_off);
        context__.validate_dims("parameter initialization", "B_z", "vector_d", context__.to_vec(n_off));
        Eigen::Matrix<double, Eigen::Dynamic, 1> B_z(n_off);
        size_t B_z_j_1_max__ = n_off;
        for (size_t j_1__ = 0; j_1__ < B_z_j_1_max__; ++j_1__) {
            B_z(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(B_z);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable B_z: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 55;
        if (!(context__.contains_r("Bdiag")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable Bdiag missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("Bdiag");
        pos__ = 0U;
        validate_non_negative_index("Bdiag", "n_spp", n_spp);
        context__.validate_dims("parameter initialization", "Bdiag", "vector_d", context__.to_vec(n_spp));
        Eigen::Matrix<double, Eigen::Dynamic, 1> Bdiag(n_spp);
        size_t Bdiag_j_1_max__ = n_spp;
        for (size_t j_1__ = 0; j_1__ < Bdiag_j_1_max__; ++j_1__) {
            Bdiag(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lub_unconstrain(0, 1, Bdiag);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable Bdiag: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 56;
        if (!(context__.contains_r("x0")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable x0 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("x0");
        pos__ = 0U;
        validate_non_negative_index("x0", "n_spp", n_spp);
        context__.validate_dims("parameter initialization", "x0", "vector_d", context__.to_vec(n_spp));
        Eigen::Matrix<double, Eigen::Dynamic, 1> x0(n_spp);
        size_t x0_j_1_max__ = n_spp;
        for (size_t j_1__ = 0; j_1__ < x0_j_1_max__; ++j_1__) {
            x0(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(x0);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable x0: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 57;
        if (!(context__.contains_r("U")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable U missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("U");
        pos__ = 0U;
        validate_non_negative_index("U", "(est_trend * n_spp)", (est_trend * n_spp));
        context__.validate_dims("parameter initialization", "U", "vector_d", context__.to_vec((est_trend * n_spp)));
        Eigen::Matrix<double, Eigen::Dynamic, 1> U((est_trend * n_spp));
        size_t U_j_1_max__ = (est_trend * n_spp);
        for (size_t j_1__ = 0; j_1__ < U_j_1_max__; ++j_1__) {
            U(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(U);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable U: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 58;
        if (!(context__.contains_r("nu")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable nu missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("nu");
        pos__ = 0U;
        validate_non_negative_index("nu", "est_nu", est_nu);
        context__.validate_dims("parameter initialization", "nu", "vector_d", context__.to_vec(est_nu));
        Eigen::Matrix<double, Eigen::Dynamic, 1> nu(est_nu);
        size_t nu_j_1_max__ = est_nu;
        for (size_t j_1__ = 0; j_1__ < nu_j_1_max__; ++j_1__) {
            nu(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lb_unconstrain(2, nu);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable nu: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 59;
        if (!(context__.contains_r("lambda2")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable lambda2 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("lambda2");
        pos__ = 0U;
        validate_non_negative_index("lambda2", "(est_lambda * n_off)", (est_lambda * n_off));
        context__.validate_dims("parameter initialization", "lambda2", "vector_d", context__.to_vec((est_lambda * n_off)));
        Eigen::Matrix<double, Eigen::Dynamic, 1> lambda2((est_lambda * n_off));
        size_t lambda2_j_1_max__ = (est_lambda * n_off);
        for (size_t j_1__ = 0; j_1__ < lambda2_j_1_max__; ++j_1__) {
            lambda2(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lb_unconstrain(0, lambda2);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable lambda2: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 60;
        if (!(context__.contains_r("c2_hs")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable c2_hs missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("c2_hs");
        pos__ = 0U;
        validate_non_negative_index("c2_hs", "est_hs", est_hs);
        context__.validate_dims("parameter initialization", "c2_hs", "vector_d", context__.to_vec(est_hs));
        Eigen::Matrix<double, Eigen::Dynamic, 1> c2_hs(est_hs);
        size_t c2_hs_j_1_max__ = est_hs;
        for (size_t j_1__ = 0; j_1__ < c2_hs_j_1_max__; ++j_1__) {
            c2_hs(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lb_unconstrain(0, c2_hs);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable c2_hs: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 61;
        if (!(context__.contains_r("lambda")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable lambda missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("lambda");
        pos__ = 0U;
        validate_non_negative_index("lambda", "(est_hs * n_off)", (est_hs * n_off));
        context__.validate_dims("parameter initialization", "lambda", "double", context__.to_vec((est_hs * n_off)));
        std::vector<double> lambda((est_hs * n_off), double(0));
        size_t lambda_k_0_max__ = (est_hs * n_off);
        for (size_t k_0__ = 0; k_0__ < lambda_k_0_max__; ++k_0__) {
            lambda[k_0__] = vals_r__[pos__++];
        }
        size_t lambda_i_0_max__ = (est_hs * n_off);
        for (size_t i_0__ = 0; i_0__ < lambda_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lb_unconstrain(0, lambda[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable lambda: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 62;
        if (!(context__.contains_r("sigma_proc")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma_proc missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma_proc");
        pos__ = 0U;
        validate_non_negative_index("sigma_proc", "n_q", n_q);
        context__.validate_dims("parameter initialization", "sigma_proc", "double", context__.to_vec(n_q));
        std::vector<double> sigma_proc(n_q, double(0));
        size_t sigma_proc_k_0_max__ = n_q;
        for (size_t k_0__ = 0; k_0__ < sigma_proc_k_0_max__; ++k_0__) {
            sigma_proc[k_0__] = vals_r__[pos__++];
        }
        size_t sigma_proc_i_0_max__ = n_q;
        for (size_t i_0__ = 0; i_0__ < sigma_proc_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lb_unconstrain(0, sigma_proc[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma_proc: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 63;
        if (!(context__.contains_r("devs")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable devs missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("devs");
        pos__ = 0U;
        validate_non_negative_index("devs", "n_spp", n_spp);
        validate_non_negative_index("devs", "(n_time - 1)", (n_time - 1));
        context__.validate_dims("parameter initialization", "devs", "matrix_d", context__.to_vec(n_spp,(n_time - 1)));
        Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> devs(n_spp, (n_time - 1));
        size_t devs_j_2_max__ = (n_time - 1);
        size_t devs_j_1_max__ = n_spp;
        for (size_t j_2__ = 0; j_2__ < devs_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < devs_j_1_max__; ++j_1__) {
                devs(j_1__, j_2__) = vals_r__[pos__++];
            }
        }
        try {
            writer__.matrix_unconstrain(devs);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable devs: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 52;
            std::vector<local_scalar_t__> sigma_obs;
            size_t sigma_obs_d_0_max__ = n_r;
            sigma_obs.reserve(sigma_obs_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < sigma_obs_d_0_max__; ++d_0__) {
                if (jacobian__)
                    sigma_obs.push_back(in__.scalar_lb_constrain(0, lp__));
                else
                    sigma_obs.push_back(in__.scalar_lb_constrain(0));
            }
            current_statement_begin__ = 53;
            local_scalar_t__ sigma_scale;
            (void) sigma_scale;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma_scale = in__.scalar_lb_constrain(0, lp__);
            else
                sigma_scale = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 54;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> B_z;
            (void) B_z;  // dummy to suppress unused var warning
            if (jacobian__)
                B_z = in__.vector_constrain(n_off, lp__);
            else
                B_z = in__.vector_constrain(n_off);
            current_statement_begin__ = 55;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> Bdiag;
            (void) Bdiag;  // dummy to suppress unused var warning
            if (jacobian__)
                Bdiag = in__.vector_lub_constrain(0, 1, n_spp, lp__);
            else
                Bdiag = in__.vector_lub_constrain(0, 1, n_spp);
            current_statement_begin__ = 56;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> x0;
            (void) x0;  // dummy to suppress unused var warning
            if (jacobian__)
                x0 = in__.vector_constrain(n_spp, lp__);
            else
                x0 = in__.vector_constrain(n_spp);
            current_statement_begin__ = 57;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> U;
            (void) U;  // dummy to suppress unused var warning
            if (jacobian__)
                U = in__.vector_constrain((est_trend * n_spp), lp__);
            else
                U = in__.vector_constrain((est_trend * n_spp));
            current_statement_begin__ = 58;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> nu;
            (void) nu;  // dummy to suppress unused var warning
            if (jacobian__)
                nu = in__.vector_lb_constrain(2, est_nu, lp__);
            else
                nu = in__.vector_lb_constrain(2, est_nu);
            current_statement_begin__ = 59;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> lambda2;
            (void) lambda2;  // dummy to suppress unused var warning
            if (jacobian__)
                lambda2 = in__.vector_lb_constrain(0, (est_lambda * n_off), lp__);
            else
                lambda2 = in__.vector_lb_constrain(0, (est_lambda * n_off));
            current_statement_begin__ = 60;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> c2_hs;
            (void) c2_hs;  // dummy to suppress unused var warning
            if (jacobian__)
                c2_hs = in__.vector_lb_constrain(0, est_hs, lp__);
            else
                c2_hs = in__.vector_lb_constrain(0, est_hs);
            current_statement_begin__ = 61;
            std::vector<local_scalar_t__> lambda;
            size_t lambda_d_0_max__ = (est_hs * n_off);
            lambda.reserve(lambda_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < lambda_d_0_max__; ++d_0__) {
                if (jacobian__)
                    lambda.push_back(in__.scalar_lb_constrain(0, lp__));
                else
                    lambda.push_back(in__.scalar_lb_constrain(0));
            }
            current_statement_begin__ = 62;
            std::vector<local_scalar_t__> sigma_proc;
            size_t sigma_proc_d_0_max__ = n_q;
            sigma_proc.reserve(sigma_proc_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < sigma_proc_d_0_max__; ++d_0__) {
                if (jacobian__)
                    sigma_proc.push_back(in__.scalar_lb_constrain(0, lp__));
                else
                    sigma_proc.push_back(in__.scalar_lb_constrain(0));
            }
            current_statement_begin__ = 63;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> devs;
            (void) devs;  // dummy to suppress unused var warning
            if (jacobian__)
                devs = in__.matrix_constrain(n_spp, (n_time - 1), lp__);
            else
                devs = in__.matrix_constrain(n_spp, (n_time - 1));
            // transformed parameters
            current_statement_begin__ = 66;
            validate_non_negative_index("Bmat", "n_spp", n_spp);
            validate_non_negative_index("Bmat", "n_spp", n_spp);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> Bmat(n_spp, n_spp);
            stan::math::initialize(Bmat, DUMMY_VAR__);
            stan::math::fill(Bmat, DUMMY_VAR__);
            current_statement_begin__ = 67;
            validate_non_negative_index("x", "n_spp", n_spp);
            validate_non_negative_index("x", "n_time", n_time);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> x(n_spp, n_time);
            stan::math::initialize(x, DUMMY_VAR__);
            stan::math::fill(x, DUMMY_VAR__);
            current_statement_begin__ = 68;
            validate_non_negative_index("lambda_tilde", "(est_hs * n_off)", (est_hs * n_off));
            std::vector<local_scalar_t__> lambda_tilde((est_hs * n_off), local_scalar_t__(0));
            stan::math::initialize(lambda_tilde, DUMMY_VAR__);
            stan::math::fill(lambda_tilde, DUMMY_VAR__);
            current_statement_begin__ = 69;
            validate_non_negative_index("sigma", "n_spp", n_spp);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> sigma(n_spp);
            stan::math::initialize(sigma, DUMMY_VAR__);
            stan::math::fill(sigma, DUMMY_VAR__);
            current_statement_begin__ = 70;
            validate_non_negative_index("Boffd", "n_off", n_off);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> Boffd(n_off);
            stan::math::initialize(Boffd, DUMMY_VAR__);
            stan::math::fill(Boffd, DUMMY_VAR__);
            // transformed parameters block statements
            current_statement_begin__ = 73;
            if (as_bool(logical_eq(off_diag_priors, 0))) {
                current_statement_begin__ = 76;
                for (int i = 1; i <= n_off; ++i) {
                    current_statement_begin__ = 77;
                    stan::model::assign(Boffd, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                ((get_base1(B_z, i, "B_z", 1) * get_base1(b_sd, i, "b_sd", 1)) + get_base1(b_mu, i, "b_mu", 1)), 
                                "assigning variable Boffd");
                }
            }
            current_statement_begin__ = 80;
            if (as_bool(logical_eq(off_diag_priors, 1))) {
                current_statement_begin__ = 82;
                for (int i = 1; i <= n_off; ++i) {
                    current_statement_begin__ = 83;
                    stan::model::assign(Boffd, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                ((sigma_scale * stan::math::sqrt(get_base1(lambda2, i, "lambda2", 1))) * get_base1(B_z, i, "B_z", 1)), 
                                "assigning variable Boffd");
                }
            }
            current_statement_begin__ = 87;
            if (as_bool(logical_eq(off_diag_priors, 2))) {
                current_statement_begin__ = 88;
                for (int i = 1; i <= n_off; ++i) {
                    current_statement_begin__ = 90;
                    stan::model::assign(Boffd, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                ((sigma_scale * stan::math::sqrt(get_base1(lambda2, i, "lambda2", 1))) * get_base1(B_z, i, "B_z", 1)), 
                                "assigning variable Boffd");
                }
            }
            current_statement_begin__ = 94;
            if (as_bool(logical_eq(off_diag_priors, 3))) {
                current_statement_begin__ = 95;
                for (int i = 1; i <= n_off; ++i) {
                    current_statement_begin__ = 96;
                    stan::model::assign(lambda_tilde, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                stan::math::sqrt((((get_base1(c2_hs, 1, "c2_hs", 1) * get_base1(lambda, i, "lambda", 1)) * get_base1(lambda, i, "lambda", 1)) / (get_base1(c2_hs, 1, "c2_hs", 1) + square((sigma_scale * get_base1(lambda, i, "lambda", 1)))))), 
                                "assigning variable lambda_tilde");
                    current_statement_begin__ = 98;
                    stan::model::assign(Boffd, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                ((get_base1(B_z, i, "B_z", 1) * sigma_scale) * get_base1(lambda_tilde, i, "lambda_tilde", 1)), 
                                "assigning variable Boffd");
                }
            }
            current_statement_begin__ = 103;
            stan::math::assign(Bmat, diag_matrix(Bdiag));
            current_statement_begin__ = 105;
            for (int i = 1; i <= n_off; ++i) {
                current_statement_begin__ = 106;
                stan::model::assign(Bmat, 
                            stan::model::cons_list(stan::model::index_uni(get_base1(get_base1(rc_off, i, "rc_off", 1), 1, "rc_off", 2)), stan::model::cons_list(stan::model::index_uni(get_base1(get_base1(rc_off, i, "rc_off", 1), 2, "rc_off", 2)), stan::model::nil_index_list())), 
                            get_base1(Boffd, i, "Boffd", 1), 
                            "assigning variable Bmat");
            }
            current_statement_begin__ = 109;
            for (int i = 1; i <= n_spp; ++i) {
                current_statement_begin__ = 110;
                stan::model::assign(sigma, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            get_base1(sigma_proc, get_base1(id_q, i, "id_q", 1), "sigma_proc", 1), 
                            "assigning variable sigma");
            }
            current_statement_begin__ = 113;
            stan::model::assign(x, 
                        stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                        x0, 
                        "assigning variable x");
            current_statement_begin__ = 114;
            for (int t = 2; t <= n_time; ++t) {
                current_statement_begin__ = 115;
                stan::model::assign(x, 
                            stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(t), stan::model::nil_index_list())), 
                            stan::model::deep_copy(add(multiply(Bmat, stan::model::rvalue(x, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni((t - 1)), stan::model::nil_index_list())), "x")), elt_multiply(sigma, stan::model::rvalue(devs, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni((t - 1)), stan::model::nil_index_list())), "devs")))), 
                            "assigning variable x");
                current_statement_begin__ = 116;
                if (as_bool(logical_eq(est_trend, 1))) {
                    current_statement_begin__ = 117;
                    stan::model::assign(x, 
                                stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(t), stan::model::nil_index_list())), 
                                stan::model::deep_copy(add(stan::model::rvalue(x, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(t), stan::model::nil_index_list())), "x"), U)), 
                                "assigning variable x");
                }
            }
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 66;
            size_t Bmat_j_1_max__ = n_spp;
            size_t Bmat_j_2_max__ = n_spp;
            for (size_t j_1__ = 0; j_1__ < Bmat_j_1_max__; ++j_1__) {
                for (size_t j_2__ = 0; j_2__ < Bmat_j_2_max__; ++j_2__) {
                    if (stan::math::is_uninitialized(Bmat(j_1__, j_2__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: Bmat" << "(" << j_1__ << ", " << j_2__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable Bmat: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            current_statement_begin__ = 67;
            size_t x_j_1_max__ = n_spp;
            size_t x_j_2_max__ = n_time;
            for (size_t j_1__ = 0; j_1__ < x_j_1_max__; ++j_1__) {
                for (size_t j_2__ = 0; j_2__ < x_j_2_max__; ++j_2__) {
                    if (stan::math::is_uninitialized(x(j_1__, j_2__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: x" << "(" << j_1__ << ", " << j_2__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable x: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            current_statement_begin__ = 68;
            size_t lambda_tilde_k_0_max__ = (est_hs * n_off);
            for (size_t k_0__ = 0; k_0__ < lambda_tilde_k_0_max__; ++k_0__) {
                if (stan::math::is_uninitialized(lambda_tilde[k_0__])) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: lambda_tilde" << "[" << k_0__ << "]";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable lambda_tilde: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            size_t lambda_tilde_i_0_max__ = (est_hs * n_off);
            for (size_t i_0__ = 0; i_0__ < lambda_tilde_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "lambda_tilde[i_0__]", lambda_tilde[i_0__], 0);
            }
            current_statement_begin__ = 69;
            size_t sigma_j_1_max__ = n_spp;
            for (size_t j_1__ = 0; j_1__ < sigma_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(sigma(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: sigma" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable sigma: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            check_greater_or_equal(function__, "sigma", sigma, 0);
            current_statement_begin__ = 70;
            size_t Boffd_j_1_max__ = n_off;
            for (size_t j_1__ = 0; j_1__ < Boffd_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(Boffd(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: Boffd" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable Boffd: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            // model body
            current_statement_begin__ = 125;
            lp_accum__.add(std_normal_log<propto__>(x0));
            current_statement_begin__ = 126;
            for (int i = 1; i <= n_spp; ++i) {
                current_statement_begin__ = 127;
                lp_accum__.add(std_normal_log<propto__>(get_base1(devs, i, "devs", 1)));
            }
            current_statement_begin__ = 129;
            if (as_bool(logical_eq(est_trend, 1))) {
                current_statement_begin__ = 130;
                lp_accum__.add(std_normal_log<propto__>(U));
            }
            current_statement_begin__ = 133;
            lp_accum__.add(normal_log<propto__>(sigma_proc, sigma_proc_mu, sigma_proc_sd));
            current_statement_begin__ = 135;
            lp_accum__.add(normal_log<propto__>(sigma_obs, sigma_obs_mu, sigma_obs_sd));
            current_statement_begin__ = 137;
            lp_accum__.add(normal_log<propto__>(Bdiag, b_mu_diag, b_sd_diag));
            current_statement_begin__ = 139;
            lp_accum__.add(std_normal_log<propto__>(B_z));
            current_statement_begin__ = 143;
            if (as_bool(logical_eq(off_diag_priors, 1))) {
                current_statement_begin__ = 146;
                lp_accum__.add(student_t_log<propto__>(sigma_scale, sigma_scale_df, 0, sigma_scale_sd));
                current_statement_begin__ = 147;
                if (as_bool(logical_eq(est_nu, 1))) {
                    current_statement_begin__ = 148;
                    lp_accum__.add(gamma_log<propto__>(get_base1(nu, 1, "nu", 1), 2, 0.1));
                    current_statement_begin__ = 149;
                    for (int i = 1; i <= n_off; ++i) {
                        current_statement_begin__ = 150;
                        lp_accum__.add(inv_gamma_log<propto__>(get_base1(lambda2, i, "lambda2", 1), (get_base1(nu, 1, "nu", 1) / 2), (get_base1(nu, 1, "nu", 1) / 2)));
                    }
                } else {
                    current_statement_begin__ = 153;
                    for (int i = 1; i <= n_off; ++i) {
                        current_statement_begin__ = 154;
                        lp_accum__.add(inv_gamma_log<propto__>(get_base1(lambda2, i, "lambda2", 1), (nu_known / 2), (nu_known / 2)));
                    }
                }
            }
            current_statement_begin__ = 158;
            if (as_bool(logical_eq(off_diag_priors, 2))) {
                current_statement_begin__ = 160;
                lp_accum__.add(student_t_log<propto__>(sigma_scale, sigma_scale_df, 0, sigma_scale_sd));
                current_statement_begin__ = 162;
                lp_accum__.add(exponential_log<propto__>(lambda2, 0.5));
            }
            current_statement_begin__ = 164;
            if (as_bool(logical_eq(off_diag_priors, 3))) {
                current_statement_begin__ = 172;
                lp_accum__.add(student_t_log<propto__>(lambda, 1, 0.0, 1.0));
                current_statement_begin__ = 173;
                lp_accum__.add(student_t_log<propto__>(sigma_scale, 3, 0, global_scale));
                current_statement_begin__ = 174;
                lp_accum__.add(inv_gamma_log<propto__>(c2_hs, (slab_df / 2.0), (((slab_df * slab_scale) * slab_scale) / 2.0)));
            }
            current_statement_begin__ = 179;
            if (as_bool(logical_eq(priors_only, 0))) {
                current_statement_begin__ = 180;
                for (int i = 1; i <= n_pos; ++i) {
                    current_statement_begin__ = 181;
                    lp_accum__.add(normal_log<propto__>(get_base1(yy, i, "yy", 1), get_base1(x, get_base1(species_index, i, "species_index", 1), get_base1(time_index, i, "time_index", 1), "x", 1), get_base1(sigma_obs, get_base1(id_r, get_base1(species_index, i, "species_index", 1), "id_r", 1), "sigma_obs", 1)));
                }
            } else {
                current_statement_begin__ = 184;
                lp_accum__.add(normal_log<propto__>(dummy, 0, 1));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("sigma_obs");
        names__.push_back("sigma_scale");
        names__.push_back("B_z");
        names__.push_back("Bdiag");
        names__.push_back("x0");
        names__.push_back("U");
        names__.push_back("nu");
        names__.push_back("lambda2");
        names__.push_back("c2_hs");
        names__.push_back("lambda");
        names__.push_back("sigma_proc");
        names__.push_back("devs");
        names__.push_back("Bmat");
        names__.push_back("x");
        names__.push_back("lambda_tilde");
        names__.push_back("sigma");
        names__.push_back("Boffd");
        names__.push_back("log_lik");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(n_r);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_off);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_spp);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_spp);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((est_trend * n_spp));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(est_nu);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((est_lambda * n_off));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(est_hs);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((est_hs * n_off));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_q);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_spp);
        dims__.push_back((n_time - 1));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_spp);
        dims__.push_back(n_spp);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_spp);
        dims__.push_back(n_time);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((est_hs * n_off));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_spp);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_off);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_pos);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_varlasso_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        std::vector<double> sigma_obs;
        size_t sigma_obs_d_0_max__ = n_r;
        sigma_obs.reserve(sigma_obs_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < sigma_obs_d_0_max__; ++d_0__) {
            sigma_obs.push_back(in__.scalar_lb_constrain(0));
        }
        size_t sigma_obs_k_0_max__ = n_r;
        for (size_t k_0__ = 0; k_0__ < sigma_obs_k_0_max__; ++k_0__) {
            vars__.push_back(sigma_obs[k_0__]);
        }
        double sigma_scale = in__.scalar_lb_constrain(0);
        vars__.push_back(sigma_scale);
        Eigen::Matrix<double, Eigen::Dynamic, 1> B_z = in__.vector_constrain(n_off);
        size_t B_z_j_1_max__ = n_off;
        for (size_t j_1__ = 0; j_1__ < B_z_j_1_max__; ++j_1__) {
            vars__.push_back(B_z(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> Bdiag = in__.vector_lub_constrain(0, 1, n_spp);
        size_t Bdiag_j_1_max__ = n_spp;
        for (size_t j_1__ = 0; j_1__ < Bdiag_j_1_max__; ++j_1__) {
            vars__.push_back(Bdiag(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> x0 = in__.vector_constrain(n_spp);
        size_t x0_j_1_max__ = n_spp;
        for (size_t j_1__ = 0; j_1__ < x0_j_1_max__; ++j_1__) {
            vars__.push_back(x0(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> U = in__.vector_constrain((est_trend * n_spp));
        size_t U_j_1_max__ = (est_trend * n_spp);
        for (size_t j_1__ = 0; j_1__ < U_j_1_max__; ++j_1__) {
            vars__.push_back(U(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> nu = in__.vector_lb_constrain(2, est_nu);
        size_t nu_j_1_max__ = est_nu;
        for (size_t j_1__ = 0; j_1__ < nu_j_1_max__; ++j_1__) {
            vars__.push_back(nu(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> lambda2 = in__.vector_lb_constrain(0, (est_lambda * n_off));
        size_t lambda2_j_1_max__ = (est_lambda * n_off);
        for (size_t j_1__ = 0; j_1__ < lambda2_j_1_max__; ++j_1__) {
            vars__.push_back(lambda2(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> c2_hs = in__.vector_lb_constrain(0, est_hs);
        size_t c2_hs_j_1_max__ = est_hs;
        for (size_t j_1__ = 0; j_1__ < c2_hs_j_1_max__; ++j_1__) {
            vars__.push_back(c2_hs(j_1__));
        }
        std::vector<double> lambda;
        size_t lambda_d_0_max__ = (est_hs * n_off);
        lambda.reserve(lambda_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < lambda_d_0_max__; ++d_0__) {
            lambda.push_back(in__.scalar_lb_constrain(0));
        }
        size_t lambda_k_0_max__ = (est_hs * n_off);
        for (size_t k_0__ = 0; k_0__ < lambda_k_0_max__; ++k_0__) {
            vars__.push_back(lambda[k_0__]);
        }
        std::vector<double> sigma_proc;
        size_t sigma_proc_d_0_max__ = n_q;
        sigma_proc.reserve(sigma_proc_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < sigma_proc_d_0_max__; ++d_0__) {
            sigma_proc.push_back(in__.scalar_lb_constrain(0));
        }
        size_t sigma_proc_k_0_max__ = n_q;
        for (size_t k_0__ = 0; k_0__ < sigma_proc_k_0_max__; ++k_0__) {
            vars__.push_back(sigma_proc[k_0__]);
        }
        Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> devs = in__.matrix_constrain(n_spp, (n_time - 1));
        size_t devs_j_2_max__ = (n_time - 1);
        size_t devs_j_1_max__ = n_spp;
        for (size_t j_2__ = 0; j_2__ < devs_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < devs_j_1_max__; ++j_1__) {
                vars__.push_back(devs(j_1__, j_2__));
            }
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 66;
            validate_non_negative_index("Bmat", "n_spp", n_spp);
            validate_non_negative_index("Bmat", "n_spp", n_spp);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> Bmat(n_spp, n_spp);
            stan::math::initialize(Bmat, DUMMY_VAR__);
            stan::math::fill(Bmat, DUMMY_VAR__);
            current_statement_begin__ = 67;
            validate_non_negative_index("x", "n_spp", n_spp);
            validate_non_negative_index("x", "n_time", n_time);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> x(n_spp, n_time);
            stan::math::initialize(x, DUMMY_VAR__);
            stan::math::fill(x, DUMMY_VAR__);
            current_statement_begin__ = 68;
            validate_non_negative_index("lambda_tilde", "(est_hs * n_off)", (est_hs * n_off));
            std::vector<double> lambda_tilde((est_hs * n_off), double(0));
            stan::math::initialize(lambda_tilde, DUMMY_VAR__);
            stan::math::fill(lambda_tilde, DUMMY_VAR__);
            current_statement_begin__ = 69;
            validate_non_negative_index("sigma", "n_spp", n_spp);
            Eigen::Matrix<double, Eigen::Dynamic, 1> sigma(n_spp);
            stan::math::initialize(sigma, DUMMY_VAR__);
            stan::math::fill(sigma, DUMMY_VAR__);
            current_statement_begin__ = 70;
            validate_non_negative_index("Boffd", "n_off", n_off);
            Eigen::Matrix<double, Eigen::Dynamic, 1> Boffd(n_off);
            stan::math::initialize(Boffd, DUMMY_VAR__);
            stan::math::fill(Boffd, DUMMY_VAR__);
            // do transformed parameters statements
            current_statement_begin__ = 73;
            if (as_bool(logical_eq(off_diag_priors, 0))) {
                current_statement_begin__ = 76;
                for (int i = 1; i <= n_off; ++i) {
                    current_statement_begin__ = 77;
                    stan::model::assign(Boffd, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                ((get_base1(B_z, i, "B_z", 1) * get_base1(b_sd, i, "b_sd", 1)) + get_base1(b_mu, i, "b_mu", 1)), 
                                "assigning variable Boffd");
                }
            }
            current_statement_begin__ = 80;
            if (as_bool(logical_eq(off_diag_priors, 1))) {
                current_statement_begin__ = 82;
                for (int i = 1; i <= n_off; ++i) {
                    current_statement_begin__ = 83;
                    stan::model::assign(Boffd, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                ((sigma_scale * stan::math::sqrt(get_base1(lambda2, i, "lambda2", 1))) * get_base1(B_z, i, "B_z", 1)), 
                                "assigning variable Boffd");
                }
            }
            current_statement_begin__ = 87;
            if (as_bool(logical_eq(off_diag_priors, 2))) {
                current_statement_begin__ = 88;
                for (int i = 1; i <= n_off; ++i) {
                    current_statement_begin__ = 90;
                    stan::model::assign(Boffd, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                ((sigma_scale * stan::math::sqrt(get_base1(lambda2, i, "lambda2", 1))) * get_base1(B_z, i, "B_z", 1)), 
                                "assigning variable Boffd");
                }
            }
            current_statement_begin__ = 94;
            if (as_bool(logical_eq(off_diag_priors, 3))) {
                current_statement_begin__ = 95;
                for (int i = 1; i <= n_off; ++i) {
                    current_statement_begin__ = 96;
                    stan::model::assign(lambda_tilde, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                stan::math::sqrt((((get_base1(c2_hs, 1, "c2_hs", 1) * get_base1(lambda, i, "lambda", 1)) * get_base1(lambda, i, "lambda", 1)) / (get_base1(c2_hs, 1, "c2_hs", 1) + square((sigma_scale * get_base1(lambda, i, "lambda", 1)))))), 
                                "assigning variable lambda_tilde");
                    current_statement_begin__ = 98;
                    stan::model::assign(Boffd, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                ((get_base1(B_z, i, "B_z", 1) * sigma_scale) * get_base1(lambda_tilde, i, "lambda_tilde", 1)), 
                                "assigning variable Boffd");
                }
            }
            current_statement_begin__ = 103;
            stan::math::assign(Bmat, diag_matrix(Bdiag));
            current_statement_begin__ = 105;
            for (int i = 1; i <= n_off; ++i) {
                current_statement_begin__ = 106;
                stan::model::assign(Bmat, 
                            stan::model::cons_list(stan::model::index_uni(get_base1(get_base1(rc_off, i, "rc_off", 1), 1, "rc_off", 2)), stan::model::cons_list(stan::model::index_uni(get_base1(get_base1(rc_off, i, "rc_off", 1), 2, "rc_off", 2)), stan::model::nil_index_list())), 
                            get_base1(Boffd, i, "Boffd", 1), 
                            "assigning variable Bmat");
            }
            current_statement_begin__ = 109;
            for (int i = 1; i <= n_spp; ++i) {
                current_statement_begin__ = 110;
                stan::model::assign(sigma, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            get_base1(sigma_proc, get_base1(id_q, i, "id_q", 1), "sigma_proc", 1), 
                            "assigning variable sigma");
            }
            current_statement_begin__ = 113;
            stan::model::assign(x, 
                        stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                        x0, 
                        "assigning variable x");
            current_statement_begin__ = 114;
            for (int t = 2; t <= n_time; ++t) {
                current_statement_begin__ = 115;
                stan::model::assign(x, 
                            stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(t), stan::model::nil_index_list())), 
                            stan::model::deep_copy(add(multiply(Bmat, stan::model::rvalue(x, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni((t - 1)), stan::model::nil_index_list())), "x")), elt_multiply(sigma, stan::model::rvalue(devs, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni((t - 1)), stan::model::nil_index_list())), "devs")))), 
                            "assigning variable x");
                current_statement_begin__ = 116;
                if (as_bool(logical_eq(est_trend, 1))) {
                    current_statement_begin__ = 117;
                    stan::model::assign(x, 
                                stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(t), stan::model::nil_index_list())), 
                                stan::model::deep_copy(add(stan::model::rvalue(x, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(t), stan::model::nil_index_list())), "x"), U)), 
                                "assigning variable x");
                }
            }
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 68;
            size_t lambda_tilde_i_0_max__ = (est_hs * n_off);
            for (size_t i_0__ = 0; i_0__ < lambda_tilde_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "lambda_tilde[i_0__]", lambda_tilde[i_0__], 0);
            }
            current_statement_begin__ = 69;
            check_greater_or_equal(function__, "sigma", sigma, 0);
            // write transformed parameters
            if (include_tparams__) {
                size_t Bmat_j_2_max__ = n_spp;
                size_t Bmat_j_1_max__ = n_spp;
                for (size_t j_2__ = 0; j_2__ < Bmat_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < Bmat_j_1_max__; ++j_1__) {
                        vars__.push_back(Bmat(j_1__, j_2__));
                    }
                }
                size_t x_j_2_max__ = n_time;
                size_t x_j_1_max__ = n_spp;
                for (size_t j_2__ = 0; j_2__ < x_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < x_j_1_max__; ++j_1__) {
                        vars__.push_back(x(j_1__, j_2__));
                    }
                }
                size_t lambda_tilde_k_0_max__ = (est_hs * n_off);
                for (size_t k_0__ = 0; k_0__ < lambda_tilde_k_0_max__; ++k_0__) {
                    vars__.push_back(lambda_tilde[k_0__]);
                }
                size_t sigma_j_1_max__ = n_spp;
                for (size_t j_1__ = 0; j_1__ < sigma_j_1_max__; ++j_1__) {
                    vars__.push_back(sigma(j_1__));
                }
                size_t Boffd_j_1_max__ = n_off;
                for (size_t j_1__ = 0; j_1__ < Boffd_j_1_max__; ++j_1__) {
                    vars__.push_back(Boffd(j_1__));
                }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 189;
            validate_non_negative_index("log_lik", "n_pos", n_pos);
            Eigen::Matrix<double, Eigen::Dynamic, 1> log_lik(n_pos);
            stan::math::initialize(log_lik, DUMMY_VAR__);
            stan::math::fill(log_lik, DUMMY_VAR__);
            // generated quantities statements
            current_statement_begin__ = 190;
            if (as_bool(logical_eq(priors_only, 0))) {
                current_statement_begin__ = 191;
                for (int i = 1; i <= n_pos; ++i) {
                    current_statement_begin__ = 192;
                    stan::model::assign(log_lik, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                normal_log(get_base1(yy, i, "yy", 1), get_base1(x, get_base1(species_index, i, "species_index", 1), get_base1(time_index, i, "time_index", 1), "x", 1), get_base1(sigma_obs, get_base1(id_r, get_base1(species_index, i, "species_index", 1), "id_r", 1), "sigma_obs", 1)), 
                                "assigning variable log_lik");
                }
            }
            // validate, write generated quantities
            current_statement_begin__ = 189;
            size_t log_lik_j_1_max__ = n_pos;
            for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
                vars__.push_back(log_lik(j_1__));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_varlasso";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t sigma_obs_k_0_max__ = n_r;
        for (size_t k_0__ = 0; k_0__ < sigma_obs_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "sigma_obs" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma_scale";
        param_names__.push_back(param_name_stream__.str());
        size_t B_z_j_1_max__ = n_off;
        for (size_t j_1__ = 0; j_1__ < B_z_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "B_z" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t Bdiag_j_1_max__ = n_spp;
        for (size_t j_1__ = 0; j_1__ < Bdiag_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "Bdiag" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t x0_j_1_max__ = n_spp;
        for (size_t j_1__ = 0; j_1__ < x0_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "x0" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t U_j_1_max__ = (est_trend * n_spp);
        for (size_t j_1__ = 0; j_1__ < U_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "U" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t nu_j_1_max__ = est_nu;
        for (size_t j_1__ = 0; j_1__ < nu_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "nu" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t lambda2_j_1_max__ = (est_lambda * n_off);
        for (size_t j_1__ = 0; j_1__ < lambda2_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lambda2" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t c2_hs_j_1_max__ = est_hs;
        for (size_t j_1__ = 0; j_1__ < c2_hs_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "c2_hs" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t lambda_k_0_max__ = (est_hs * n_off);
        for (size_t k_0__ = 0; k_0__ < lambda_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lambda" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t sigma_proc_k_0_max__ = n_q;
        for (size_t k_0__ = 0; k_0__ < sigma_proc_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "sigma_proc" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t devs_j_2_max__ = (n_time - 1);
        size_t devs_j_1_max__ = n_spp;
        for (size_t j_2__ = 0; j_2__ < devs_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < devs_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "devs" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t Bmat_j_2_max__ = n_spp;
            size_t Bmat_j_1_max__ = n_spp;
            for (size_t j_2__ = 0; j_2__ < Bmat_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < Bmat_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "Bmat" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t x_j_2_max__ = n_time;
            size_t x_j_1_max__ = n_spp;
            for (size_t j_2__ = 0; j_2__ < x_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < x_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "x" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t lambda_tilde_k_0_max__ = (est_hs * n_off);
            for (size_t k_0__ = 0; k_0__ < lambda_tilde_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "lambda_tilde" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t sigma_j_1_max__ = n_spp;
            for (size_t j_1__ = 0; j_1__ < sigma_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "sigma" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t Boffd_j_1_max__ = n_off;
            for (size_t j_1__ = 0; j_1__ < Boffd_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "Boffd" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
        size_t log_lik_j_1_max__ = n_pos;
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t sigma_obs_k_0_max__ = n_r;
        for (size_t k_0__ = 0; k_0__ < sigma_obs_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "sigma_obs" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma_scale";
        param_names__.push_back(param_name_stream__.str());
        size_t B_z_j_1_max__ = n_off;
        for (size_t j_1__ = 0; j_1__ < B_z_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "B_z" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t Bdiag_j_1_max__ = n_spp;
        for (size_t j_1__ = 0; j_1__ < Bdiag_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "Bdiag" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t x0_j_1_max__ = n_spp;
        for (size_t j_1__ = 0; j_1__ < x0_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "x0" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t U_j_1_max__ = (est_trend * n_spp);
        for (size_t j_1__ = 0; j_1__ < U_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "U" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t nu_j_1_max__ = est_nu;
        for (size_t j_1__ = 0; j_1__ < nu_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "nu" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t lambda2_j_1_max__ = (est_lambda * n_off);
        for (size_t j_1__ = 0; j_1__ < lambda2_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lambda2" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t c2_hs_j_1_max__ = est_hs;
        for (size_t j_1__ = 0; j_1__ < c2_hs_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "c2_hs" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t lambda_k_0_max__ = (est_hs * n_off);
        for (size_t k_0__ = 0; k_0__ < lambda_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lambda" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t sigma_proc_k_0_max__ = n_q;
        for (size_t k_0__ = 0; k_0__ < sigma_proc_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "sigma_proc" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t devs_j_2_max__ = (n_time - 1);
        size_t devs_j_1_max__ = n_spp;
        for (size_t j_2__ = 0; j_2__ < devs_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < devs_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "devs" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t Bmat_j_2_max__ = n_spp;
            size_t Bmat_j_1_max__ = n_spp;
            for (size_t j_2__ = 0; j_2__ < Bmat_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < Bmat_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "Bmat" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t x_j_2_max__ = n_time;
            size_t x_j_1_max__ = n_spp;
            for (size_t j_2__ = 0; j_2__ < x_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < x_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "x" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t lambda_tilde_k_0_max__ = (est_hs * n_off);
            for (size_t k_0__ = 0; k_0__ < lambda_tilde_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "lambda_tilde" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t sigma_j_1_max__ = n_spp;
            for (size_t j_1__ = 0; j_1__ < sigma_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "sigma" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t Boffd_j_1_max__ = n_off;
            for (size_t j_1__ = 0; j_1__ < Boffd_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "Boffd" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
        size_t log_lik_j_1_max__ = n_pos;
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
}; // model
}  // namespace
typedef model_varlasso_namespace::model_varlasso stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
